version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_PASSWORD: lm123
      POSTGRES_USER: layer-modeller
      POSTGRES_DB: layer-modeller-database
    ports:
      - 15432:5432
  app:
    image: layer-modeller-app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports: 
     - 13000:3000